"""backtest viz indicators sltp

Revision ID: 3ca6a8351dba
Revises: 6960966b39b8
Create Date: 2026-06-12 20:07:23.312030
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ca6a8351dba'
down_revision: str | None = '6960966b39b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_run', sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('backtest_trade', sa.Column('sl', sa.Numeric(), nullable=True))
    op.add_column('backtest_trade', sa.Column('tp', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_trade', 'tp')
    op.drop_column('backtest_trade', 'sl')
    op.drop_column('backtest_run', 'indicators')
    # ### end Alembic commands ###
