"""backtest market leverage

Revision ID: 3d53f1accfea
Revises: 962142f491da
Create Date: 2026-06-12 19:07:06.062083
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d53f1accfea'
down_revision: str | None = '962142f491da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_run', sa.Column('market', sa.String(), nullable=True))
    op.add_column('backtest_run', sa.Column('leverage', sa.Integer(), nullable=True))
    # NOTE: bỏ drop 'kline_ts_idx' — index do Timescale hypertable quản lý.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_run', 'leverage')
    op.drop_column('backtest_run', 'market')
    # ### end Alembic commands ###
