"""scan sltp cols

Revision ID: 962142f491da
Revises: 39fe80684728
Create Date: 2026-06-12 15:54:28.046823
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '962142f491da'
down_revision: str | None = '39fe80684728'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: bỏ drop 'kline_ts_idx' — index do Timescale hypertable quản lý.
    op.add_column('scan_result', sa.Column('entry', sa.Numeric(), nullable=True))
    op.add_column('scan_result', sa.Column('atr', sa.Numeric(), nullable=True))
    op.add_column('scan_result', sa.Column('sl', sa.Numeric(), nullable=True))
    op.add_column('scan_result', sa.Column('tp', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_result', 'tp')
    op.drop_column('scan_result', 'sl')
    op.drop_column('scan_result', 'atr')
    op.drop_column('scan_result', 'entry')
    # ### end Alembic commands ###
