"""backtest tables

Revision ID: d9539815ac78
Revises: cf84272c8ff9
Create Date: 2026-06-12 13:10:55.064760
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9539815ac78'
down_revision: str | None = 'cf84272c8ff9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('tf', sa.String(), nullable=False),
    sa.Column('from_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capital', sa.Numeric(), nullable=True),
    sa.Column('fee_rate', sa.Numeric(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(), nullable=True),
    sa.Column('winrate', sa.Numeric(), nullable=True),
    sa.Column('max_dd', sa.Numeric(), nullable=True),
    sa.Column('sharpe', sa.Numeric(), nullable=True),
    sa.Column('n_trades', sa.Integer(), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('entry_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry', sa.Numeric(), nullable=True),
    sa.Column('exit_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit', sa.Numeric(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: bỏ drop 'kline_ts_idx' — index do Timescale hypertable quản lý.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_trade')
    op.drop_table('backtest_run')
    # ### end Alembic commands ###
