"""strategy bot order position

Revision ID: f4e62b2af69c
Revises: 0001
Create Date: 2026-06-12 12:24:14.326835
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4e62b2af69c'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_strategy_name_version')
    )
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('tf', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('PAPER','TESTNET','LIVE')", name='ck_bot_mode'),
    sa.CheckConstraint("status IN ('RUNNING','PAUSED','STOPPED')", name='ck_bot_status'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('ext_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sl', sa.Numeric(), nullable=True),
    sa.Column('tp', sa.Numeric(), nullable=True),
    sa.Column('filled_qty', sa.Numeric(), nullable=False),
    sa.Column('avg_price', sa.Numeric(), nullable=True),
    sa.Column('fee', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_order_side'),
    sa.CheckConstraint("source IN ('BOT','MANUAL','SYSTEM')", name='ck_order_source'),
    sa.CheckConstraint("status IN ('NEW','FILLED','PARTIAL','CANCELLED','REJECTED')", name='ck_order_status'),
    sa.CheckConstraint("type IN ('MARKET','LIMIT')", name='ck_order_type'),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('sl', sa.Numeric(), nullable=True),
    sa.Column('tp', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_price', sa.Numeric(), nullable=True),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("side IN ('LONG','SHORT')", name='ck_position_side'),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_position_status'),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: bỏ drop 'kline_ts_idx' — index này do Timescale hypertable quản lý, không phải Alembic.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('order')
    op.drop_table('bot')
    op.drop_table('strategy')
    # ### end Alembic commands ###
