// Giải thích thuật ngữ/chỉ số — hiển thị trong tooltip khi hover.
export const GLOSSARY: Record<string, string> = {
  pnl_pct: "Lợi nhuận ròng trên vốn (%), đã trừ phí. Dương = lãi.",
  winrate: "Tỉ lệ lệnh có lãi trên tổng số lệnh (%).",
  max_dd: "Sụt vốn lớn nhất từ đỉnh xuống đáy (%). Càng thấp càng ít rủi ro; đòn bẩy nhân lên.",
  sharpe: "Lợi nhuận điều chỉnh theo rủi ro (return / độ biến động). > 1 là tốt.",
  n_trades: "Tổng số lệnh đã đóng. Quá ít → dễ overfit, kết quả thiếu tin cậy.",
  score: "Điểm sức mạnh tín hiệu (0–100), từ RSI + động lượng. Cao = tín hiệu rõ.",
  signal: "Hướng đề xuất: BUY (mua/long), SELL (bán/short), NEUTRAL (đứng ngoài).",
  entry: "Giá hiện tại — điểm vào dự kiến.",
  atr: "Average True Range — biên dao động trung bình (đo biến động giá).",
  sl: "Stop-loss: giá cắt lỗ tự động. Bot tự đóng khi chạm.",
  tp: "Take-profit: giá chốt lời tự động. Bot tự đóng khi chạm.",
  leverage: "Đòn bẩy (Futures): nhân lãi, lỗ VÀ phí theo bội số. Rủi ro cháy tài khoản cao.",
  fee: "Phí giao dịch mỗi chiều (Binance taker: Spot 0.1%, Futures 0.05%).",
  market: "Thị trường: Spot (giao ngay) hoặc Futures (hợp đồng tương lai, có đòn bẩy).",
  mark: "Giá thị trường hiện tại (mark price) để tính lãi/lỗ tạm.",
  pnl: "Lãi/lỗ của vị thế (chưa đóng = theo giá hiện tại).",
  qty: "Khối lượng (số lượng base, vd 0.01 BTC).",
  side: "Chiều lệnh/vị thế: LONG/BUY (kỳ vọng tăng) · SHORT/SELL (kỳ vọng giảm).",
  ext_id: "Mã lệnh trên sàn (testnet/live).",
  status: "Trạng thái lệnh: NEW (chờ) · FILLED (đã khớp) · CANCELLED (đã hủy).",
  source: "Nguồn lệnh: BOT (tự động) · MANUAL (tay) · SYSTEM (hệ thống, vd auto-pause).",
};
