// Explanations of terms/metrics — shown in a tooltip on hover.
// Values are English source strings; consumers pass them through t() at render time.
export const GLOSSARY: Record<string, string> = {
  pnl_pct: "Net return on capital (%), after fees. Positive = profit.",
  winrate: "Share of winning trades out of all trades (%).",
  max_dd: "Largest peak-to-trough equity drawdown (%). Lower = less risk; leverage amplifies it.",
  sharpe: "Risk-adjusted return (return / volatility). > 1 is good.",
  n_trades: "Total closed trades. Too few → easy to overfit, results less reliable.",
  score: "Signal strength score (0–100), from RSI + momentum. Higher = clearer signal.",
  signal: "Suggested direction: BUY (long), SELL (short), NEUTRAL (stay out).",
  entry: "Current price — the expected entry point.",
  atr: "Average True Range — average price range (measures volatility).",
  sl: "Stop-loss: automatic loss-cutting price. The bot closes the position when hit.",
  tp: "Take-profit: automatic profit-taking price. The bot closes the position when hit.",
  leverage: "Leverage (Futures): multiplies profit, loss AND fees. High risk of liquidation.",
  fee: "Trading fee per side (Binance taker: Spot 0.1%, Futures 0.05%).",
  market: "Market: Spot or Futures (derivatives contracts, with leverage).",
  mark: "Current market price (mark price) used for unrealized PnL.",
  pnl: "Position profit/loss (open = at the current price).",
  qty: "Quantity (in base asset, e.g. 0.01 BTC).",
  side: "Order/position side: LONG/BUY (expects a rise) · SHORT/SELL (expects a fall).",
  ext_id: "Order ID on the exchange (testnet/live).",
  status: "Order status: NEW (pending) · FILLED · CANCELLED.",
  r: "Risk multiple: profit/loss divided by the initial entry→SL distance. +2R = gained twice the accepted risk; -1R = stopped out as planned.",
  mfe: "Max Favorable Excursion — furthest the price moved IN YOUR FAVOUR while the trade was open (% and R). High MFE but closed at a loss → TP/trade management not optimal.",
  mae: "Max Adverse Excursion — furthest the price moved AGAINST you while the trade was open (% and R). Winners with MAE near -1R → SL is tight.",
  source: "Order source: BOT (automated) · MANUAL · SYSTEM (e.g. auto-pause).",
};
